/*
------------------------------------------------
Generated by Cradle 2.0.0.0 on 7/24/2016 11:35:51 AM
https://github.com/daterre/Cradle

Original file: SugarTests.html
Story format: Sugar
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Sugar;

public partial class @SugarTests: Cradle.StoryFormats.Sugar.SugarStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly UnityTwineTestMacros macros1;

	@SugarTests()
	{
		this.StartPassage = "FenderBender";

		base.Vars = new VarDefs() { Story = this, StrictMode = false };

		macros1 = new UnityTwineTestMacros() { Story = this };
	}
	
	void Awake() {
		base.Init();
		passage1_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: FenderBender

	void passage1_Init()
	{
		this.Passages[@"FenderBender"] = new StoryPassage(@"FenderBender", new string[]{  }, passage1_Main);
	}

	#line 1 "FenderBender"
	IStoryThread passage1_Main()
	{
		yield return text(@"That's it, pretty much");
		yield return lineBreak();
		yield break;
	}


}