/*
------------------------------------------------
Generated by Cradle 2.0.0.0 on 9/29/2016 11:08:57 AM
https://github.com/daterre/Cradle

Original file: SnoozingStoryV2.html
Story format: Sugar
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Sugar;

public partial class @SnoozingStoryV2: Cradle.StoryFormats.Sugar.SugarStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("again", () => this.@again, val => this.@again = val);
		}

		public StoryVar @again;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly UnityTwineTestMacros macros1;

	@SnoozingStoryV2()
	{
		this.StartPassage = "Start";

		base.Vars = new VarDefs() { Story = this, StrictMode = false };

		macros1 = new UnityTwineTestMacros() { Story = this };
	}
	
	void Awake() {
		base.Init();
		passage0_Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
	}

	// ---------------
	#endregion

	// .............
	// #0: street3

	void passage0_Init()
	{
		this.Passages[@"street3"] = new StoryPassage(@"street3", new string[]{  }, passage0_Main);
	}

	IStoryThread passage0_Main()
	{
		SendMessage("WaitForSeconds", (float) (1)); yield return null;
		yield return text(@"She put it in my bag");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Her lips touched it");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Lips");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"touched");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"continue=", @"alarm", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #1: relationship

	void passage1_Init()
	{
		this.Passages[@"relationship"] = new StoryPassage(@"relationship", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		SendMessage("WaitForClick"); yield return null;
		yield return text(@"She knows it.");
		yield return lineBreak();
		SendMessage("WaitForClick"); yield return null;
		yield return text(@"She looks at you,");
		yield return lineBreak();
		SendMessage("WaitForClick"); yield return null;
		yield return text(@"and she knows it.");
		yield return lineBreak();
		SendMessage("WaitForClick"); yield return null;
		yield return text(@"Pretends not to.");
		yield return lineBreak();
		SendMessage("WaitForClick"); yield return null;
		yield return text(@"She smiles.");
		yield return lineBreak();
		SendMessage("WaitForClick"); yield return null;
		yield return text(@"She's kind.");
		yield return lineBreak();
		SendMessage("WaitForClick"); yield return null;
		yield return text(@"You're not.");
		yield return lineBreak();
		SendMessage("WaitForClick"); yield return null;
		yield return text(@"You're shit.");
		yield return lineBreak();
		SendMessage("WaitForClick"); yield return null;
		yield return text(@"A little shit,");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"continue=", @"alarm", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2: her

	void passage2_Init()
	{
		this.Passages[@"her"] = new StoryPassage(@"her", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text(@"why");
		yield return lineBreak();
		yield return text(@"can't");
		yield return lineBreak();
		yield return text(@"i");
		yield return lineBreak();
		yield return text(@"see");
		yield return lineBreak();
		yield return text(@"you");
		yield return lineBreak();
		yield return link(@"continue=", @"alarm", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3: script

	void passage3_Init()
	{
		this.Passages[@"script"] = new StoryPassage(@"script", new string[]{ "script", }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield break;
	}


	// .............
	// #4: alarm

	void passage4_Init()
	{
		this.Passages[@"alarm"] = new StoryPassage(@"alarm", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		SendMessage("WaitForSeconds", (float) (1)); yield return null;
		yield return text(@"...");
		yield return lineBreak();
		yield return lineBreak();
		if (! Vars.again)
		{
			SendMessage("WaitForSeconds", (float) (2)); yield return null;
			yield return text(@"? ?");
			yield return lineBreak();
		}
		SendMessage("WaitForSeconds", (float) (1.5)); yield return null;
		yield return text(@"My alarm clock.");
		yield return lineBreak();
		yield return lineBreak();
		SendMessage("WaitForSeconds", (float) (1.5)); yield return null;
		yield return link(@"Time to get up.", @"getUp", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@" ");
		if (visited("her", "relationship", "work", "street", "sea"))
		{
			yield return text(@" ");
			yield return link(@"snooze=", @"alone", null);
			yield return text(@" ");
		}
		else
		{
			yield return text(@" ");
			yield return link(@"snooze=", @"snooze", null);
			yield return text(@" ");
			Vars.again=true;
			yield return text(@" ");
		}
		yield return lineBreak();
		yield break;
	}


	// .............
	// #5: work

	void passage5_Init()
	{
		this.Passages[@"work"] = new StoryPassage(@"work", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text(@"Two days till the meeting.");
		yield return lineBreak();
		yield return text(@"Two days.");
		yield return lineBreak();
		yield return text(@"Everyone is going to");
		yield return lineBreak();
		yield return text(@"hate me.");
		yield return lineBreak();
		yield return text(@"Who needs this. Why");
		yield return lineBreak();
		yield return text(@"me");
		yield return lineBreak();
		yield return link(@"continue=", @"alarm", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #6: Start

	void passage6_Init()
	{
		this.Passages[@"Start"] = new StoryPassage(@"Start", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return abort(goToPassage: "alarm");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #7: street

	void passage7_Init()
	{
		this.Passages[@"street"] = new StoryPassage(@"street", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		SendMessage("WaitForSeconds", (float) (1)); yield return null;
		yield return text(@"I'm late. ");
		yield return lineBreak();
		yield return text(@"Where are my keys?");
		yield return lineBreak();
		yield return text(@"Shit.");
		yield return lineBreak();
		yield return link(@"continue=", @"street2", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #8: sea

	void passage8_Init()
	{
		this.Passages[@"sea"] = new StoryPassage(@"sea", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		SendMessage("WaitForClick"); yield return null;
		yield return lineBreak();
		yield return text(@"i can breath");
		yield return lineBreak();
		SendMessage("WaitForClick"); yield return null;
		yield return lineBreak();
		yield return text(@"i can fly");
		yield return lineBreak();
		SendMessage("WaitForClick"); yield return null;
		yield return lineBreak();
		yield return text(@"i can't see the sky.");
		yield return lineBreak();
		SendMessage("WaitForClick"); yield return null;
		yield return lineBreak();
		yield return text(@"it's warm");
		yield return lineBreak();
		SendMessage("WaitForClick"); yield return null;
		yield return lineBreak();
		yield return text(@"just go deep");
		yield return lineBreak();
		SendMessage("WaitForClick"); yield return null;
		yield return lineBreak();
		yield return text(@"i will always sleep");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"continue=", @"alarm", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #9: snooze

	void passage9_Init()
	{
		this.Passages[@"snooze"] = new StoryPassage(@"snooze", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		SendMessage("WaitForSeconds", (float) (1)); yield return null;
		yield return lineBreak();
		yield return text(either("I can't handle this right now.", "Keep my eyes closed."));
		yield return lineBreak();
		yield return link(@"street=", @"street", null);
		yield return lineBreak();
		yield return link(@"sea=", @"sea", null);
		yield return lineBreak();
		yield return link(@"her=", @"her", null);
		yield return lineBreak();
		yield return link(@"work=", @"work", null);
		yield return lineBreak();
		yield return link(@"relationship=", @"relationship", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #10: StoryTitle

	void passage10_Init()
	{
		this.Passages[@"StoryTitle"] = new StoryPassage(@"StoryTitle", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text(@"Snoozing");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #11: alone

	void passage11_Init()
	{
		this.Passages[@"alone"] = new StoryPassage(@"alone", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		SendMessage("WaitForSeconds", (float) (4)); yield return null;
		yield return text(@"My empty body,");
		yield return lineBreak();
		SendMessage("WaitForSeconds", (float) (2)); yield return null;
		yield return text(@"please get up.");
		yield return lineBreak();
		SendMessage("WaitForSeconds", (float) (4)); yield return null;
		yield return lineBreak();
		yield return link(@"Please.", @"getUp", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #12: street2

	void passage12_Init()
	{
		this.Passages[@"street2"] = new StoryPassage(@"street2", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		SendMessage("WaitForSeconds", (float) (1)); yield return null;
		yield return text(@"My bag is empty.");
		yield return lineBreak();
		yield return text(@"No, it's not.");
		yield return lineBreak();
		yield return text(@"There's a half-eaten sandwich.");
		yield return lineBreak();
		yield return text(@"It's hers.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"continue=", @"street3", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #13: getUp

	void passage13_Init()
	{
		this.Passages[@"getUp"] = new StoryPassage(@"getUp", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text(either("here it goes again", "out of coffee", "just breath", "must leave at 7:00"));
		yield return lineBreak();
		yield return lineBreak();
		SendMessage("WaitForSeconds", (float) (5)); yield return null;
		yield return text(@"THE END");
		yield return lineBreak();
		yield break;
	}


}